### ISSUE TITLE
[BK]: Add tests for workflow

### ISSUE THREAD

**Issue by Villarley** [VolunChain/VolunChain-Backend#10]
> [!IMPORTANT]  
Before applying, please read the [Contributors Guide](https://github.com/VolunChain/.github/blob/main/contributors_guide/readme.md). Following the guide increases your chances of being assigned to this task.

# Description
Set up a GitHub Actions workflow to automate testing for the project using Docker. The workflow will:
1. Build the Docker containers for the application and its dependencies (e.g., PostgreSQL).
2. Run all tests in a clean environment.
3. Provide feedback on whether the tests passed or failed.

# Tasks
1. Create a `.github/workflows/test.yml` file.
2. Define a workflow that:
   - Checks out the repository.
   - Sets up Node.js.
   - Builds and starts the application using Docker.
   - Runs the tests inside the Docker container.
3. Ensure the workflow uses PostgreSQL as the database for testing.

# Example Workflow Implementation
```yaml
name: CI - Run Tests with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: volunchain
          POSTGRES_PASSWORD: volunchain123
          POSTGRES_DB: volunchain_test
        ports:
          - 5432:5432
        options: >
          --health-cmd="pg_isready -U volunchain" \
          --health-interval=10s \
          --health-timeout=5s \
          --health-retries=3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          npm install

      - name: Build and Start Docker
        run: |
          docker build -t volunchain-backend .
          docker run -d --name volunchain_test --link postgres:db -e DATABASE_URL=postgresql://volunchain:volunchain123@db:5432/volunchain_test volunchain-backend

      - name: Run Tests
        run: |
          docker exec volunchain_test npm test

      - name: Stop and Remove Containers
        if: always()
        run: |
          docker stop volunchain_test
          docker rm volunchain_test
```

# Notes
1. Ensure your application supports a `DATABASE_URL` environment variable to connect to the test database.
2. The `npm test` script should be set up to run all your tests.
3. Update the workflow as needed based on your Docker and testing setup.

# Acceptance Criteria
- A `.github/workflows/test.yml` file is created with the workflow.
- The workflow builds and runs the application in Docker, connects it to PostgreSQL, and executes the tests.
- The workflow provides feedback on whether the tests passed or failed.
